version: "3.5"
services:
  charon-validator-1:
    build:
      context: charon-validator
      args:
        UPSTREAM_VERSION: v0.17.2
        LODESTAR_VERSION: v1.12.0
        CLUSTER_ID: 1
    restart: on-failure
    volumes:
      - "charon-1-data:/opt/charon/.charon"
      - "validator-1-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3811"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3831"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - "CHARON_P2P_RELAYS=https://0.relay.obol.tech,https://1.relay.obol.tech/"
      - CHARON_LOKI_SERVICE=charon-validator-1
      - CHARON_BUILDER_API=true
      - LODESTAR_EXTRA_OPTS
    ports:
      - "3811:3811/tcp"
      - "3831:3831/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-1.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
  charon-validator-2:
    build:
      context: charon-validator
      args:
        UPSTREAM_VERSION: v0.17.2
        LODESTAR_VERSION: v1.12.0
        CLUSTER_ID: 2
    restart: on-failure
    volumes:
      - "charon-2-data:/opt/charon/.charon"
      - "validator-2-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3812"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3832"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-2
      - LODESTAR_EXTRA_OPTS
    ports:
      - "3812:3812/tcp"
      - "3832:3832/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-2.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
  charon-validator-3:
    build:
      context: charon-validator
      args:
        UPSTREAM_VERSION: v0.17.2
        LODESTAR_VERSION: v1.12.0
        CLUSTER_ID: 3
    restart: on-failure
    volumes:
      - "charon-3-data:/opt/charon/.charon"
      - "validator-3-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3813"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3833"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-3
      - LODESTAR_EXTRA_OPTS
    ports:
      - "3813:3813/tcp"
      - "3833:3833/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-3.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
  charon-validator-4:
    build:
      context: charon-validator
      args:
        UPSTREAM_VERSION: v0.17.2
        LODESTAR_VERSION: v1.12.0
        CLUSTER_ID: 4
    restart: on-failure
    volumes:
      - "charon-4-data:/opt/charon/.charon"
      - "validator-4-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3814"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3834"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-4
      - LODESTAR_EXTRA_OPTS
    ports:
      - "3814:3814/tcp"
      - "3834:3834/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-4.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
  charon-validator-5:
    build:
      context: charon-validator
      args:
        UPSTREAM_VERSION: v0.17.2
        LODESTAR_VERSION: v1.12.0
        CLUSTER_ID: 5
    restart: on-failure
    volumes:
      - "charon-5-data:/opt/charon/.charon"
      - "validator-5-data:/opt/validator/data"
    environment:
      - DEFINITION_FILE_URL
      - CHARON_LOG_LEVEL=info
      - "CHARON_P2P_TCP_ADDRESS=0.0.0.0:3815"
      - "CHARON_P2P_UDP_ADDRESS=0.0.0.0:3835"
      - "CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600"
      - "CHARON_MONITORING_ADDRESS=0.0.0.0:3620"
      - "CHARON_LOKI_ADDRESSES=http://loki.dms.dappnode:3100/loki/api/v1/push"
      - CHARON_LOKI_SERVICE=charon-validator-5
      - LODESTAR_EXTRA_OPTS
    ports:
      - "3815:3815/tcp"
      - "3835:3835/udp"
    healthcheck:
      test: "wget -qO- http://localhost:3620/readyz"
    security_opt:
      - "seccomp:unconfined"
    image: "charon-validator-5.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
  prometheus:
    build:
      context: prometheus
      args:
        PROMETHEUS_VERSION: v2.46.0
    volumes:
      - "prometheus-data:/prometheus"
    restart: unless-stopped
    image: "prometheus.holesky-obol-lodestar.dnp.dappnode.eth:0.1.1"
volumes:
  charon-1-data: {}
  charon-2-data: {}
  charon-3-data: {}
  charon-4-data: {}
  charon-5-data: {}
  validator-1-data: {}
  validator-2-data: {}
  validator-3-data: {}
  validator-4-data: {}
  validator-5-data: {}
  prometheus-data: {}
